### ISSUE TITLE
chord package causes double prints

### ISSUE THREAD

**Issue by odhran456** [shahinrostami/chord#11]
I don't typically post issues so sorry if the quality of this post is below standards.
To recreate my issue, try:

import chord
print('Hello, world!')

The string 'Hello, world!' will be printed twice in the terminal. Is this expected behaviour? Can this be toggled off?

**Comment by shahinrostami** [comment]
Hi, that’s indeed strange. I can’t reproduce it on my end, can you give any more details?

**Comment by shahinrostami** [comment]
Was not able to reproduce - if you have any more details please re-open this
