### ISSUE TITLE
No module named chord

### ISSUE THREAD

**Issue by DSJourney** [shahinrostami/chord#12]
Hi, 

I came across your chord package (which seems very cool by the way), and trying to use it I could not figure out how to make it work. Since I am quite new to the whole Python scene this might be a mistake from my part but after running:

- pip install chord
- from chord import Chord 

Jupyter Lab does not recognize the module. I add two pictures below in case you can guide me on the possible steps I could give? Is there another way to set up the package?

Thanks a lot!

<img width="221" alt="Screenshot 2020-06-25 at 07 55 58" src="https://user-images.githubusercontent.com/58484051/85745272-6c938180-b6ba-11ea-93e2-9011537c7dad.png">
<img width="614" alt="Screenshot 2020-06-25 at 07 56 07" src="https://user-images.githubusercontent.com/58484051/85745267-6bfaeb00-b6ba-11ea-9d1b-6aaa32f3fb89.png">

**Comment by DSJourney** [comment]
Forget about

**Comment by DSJourney** [comment]
Forget about my post, I made a mistake with my virtual environments. It is fine!

**Comment by shahinrostami** [comment]
I'm glad you resolved it @DSJourney ! I was actually just trying to reproduce your error before getting back to you :)

**Comment by DSJourney** [comment]
> I'm glad you resolved it @DSJourney ! I was actually just trying to reproduce your error before getting back to you :)

Yeah, sorry for that... my mistake... it actually works very well thanks for putting it together.

I take the opportunity to ask, how can each connection show both numbers of the relationship, is that only on the pro version? I explain with images:

There is a relation in which, if you look from one side it occurs 2046 and if you look at it from the other side it occurs 1739

<img width="88" alt="Screenshot 2020-06-25 at 13 14 13" src="https://user-images.githubusercontent.com/58484051/85791241-5c919700-b6e6-11ea-811b-87c97a59e382.png">

When I go to the chord diagram it only shows the 2046 but not the 1739. 

<img width="245" alt="Screenshot 2020-06-25 at 13 14 03" src="https://user-images.githubusercontent.com/58484051/85791233-57344c80-b6e6-11ea-881a-742d1418d50e.png">

In your example, the matrix is symmetrical and it makes a lot of sense. But since mine is not, I was wondering if there is a way to show both values or the sum of both? I can calculate the sum but I was wondering if there was a way to make it work directly.

In any case, thanks for your work on this!
