### ISSUE TITLE
404 with the pypi link

### ISSUE THREAD

**Issue by duanpv** [shahinrostami/chord#13]
Hi Shahin,

Thanks for your great work.

Could you check the link in Installation part, pypi "Available on https://pypi.org/chord through pip:". 
Is it should be https://pypi.org/project/chord/ not https://pypi.org/chord which shows as the image below

![image](https://user-images.githubusercontent.com/9216246/86176931-aa126780-bb1d-11ea-8a5a-224c7c34eca3.png)

Best regards,
Van

**Comment by shahinrostami** [comment]
Hello @duanpv ,

Thanks for pointing that out - it's been fixed!

All the best,

Shahin
