### ISSUE TITLE
Unable to show in Visual Studio Code

### ISSUE THREAD

**Issue by AviationFreak** [shahinrostami/chord#14]
I understand that this project is built primarily with Jupyter in mind - However, I am working with Visual Studio Code and I am unable to get a Chord diagram to show using the show() or to_html() methods. Is there anything I can do to be able to display a chord diagram using this library in VSC?

Thanks!

**Comment by shahinrostami** [comment]
Hello @AviationFreak! What are you running within VSC - is it an `.ipynb` notebook or `.py` source file? I'll check it out once you let me know and see what I can do!

**Comment by AviationFreak** [comment]
@shahinrostami I'm running a .py file - Here's the pastebin: https://pastebin.com/tMZ1nzg5

(Requires Wikipedia-API)

**Comment by shahinrostami** [comment]
@AviationFreak After changing the `.show()` call to `.to_html()` (`.show()` is for Jupyter Lab only), it appears to have worked! By default, it outputs `out.html` in the current directory which contains the interactive visualisation. Would love to see how it ends up when you're finished 👍 

<img width="730" alt="Screenshot 2020-07-19 at 23 19 06" src="https://user-images.githubusercontent.com/15690380/87886614-8eacc500-ca16-11ea-86fd-51d6ad8d13cf.png">

**Comment by AviationFreak** [comment]
@shahinrostami Ah you're right! That's my bad - I didn't see the file it had generated in my overcluttered folder. Thanks for your help! :)
