### ISSUE TITLE
Only a white screen appears when running out.html

### ISSUE THREAD

**Issue by bowrango** [shahinrostami/chord#16]
A new Google Chrome tab opens up on my localhost when I run the html file, but there is no graph or anything.

**Comment by shahinrostami** [comment]
Hi! Can you share a minimal example of your code and a little more about your environment?

**Comment by bowrango** [comment]
Sure thing! I'm generating the out.html file from within my Pycharm IDE running Python 3.7. I'm on my local machine running Windows 10.

I run this to create the interactive html file, and can confirm its created:

`Chord(matrix, labels).to_html`

I then run the html file, and a tiny pop-up appears with several icons of web browsers. I select Chrome. A new Chrome tab opens, but no graph:

![result](https://user-images.githubusercontent.com/68204564/88931156-79237080-d24a-11ea-9ac7-e8a6d04f6531.png)

**Comment by shahinrostami** [comment]
Hello - can you try the attached Python file `demo.py` and let me know what the output looks like? It should output the attached `out.html` file. 

You can also use the Chrome developer tools (https://developers.google.com/web/tools/chrome-devtools/open) and see if there's an error in the console. You could also pass over the `.py` file and the `out.html` and I'll take a look!

**Comment by bowrango** [comment]
I can't seem to view the `demo.py` file, is it located somewhere in the repo?

There doesn't appear to be an issue with the HTML on the page. Here was my result, with the zipped raw file attached below:
![blank](https://user-images.githubusercontent.com/68204564/88982902-8155cd00-d297-11ea-91a5-04a6867cc1a3.png)

[out_HTML.zip](https://github.com/shahinrostami/chord/files/5004215/out_HTML.zip)

**Comment by bowrango** [comment]
I can't seem the view the `demo.py` file, is it located somewhere in the repo?

Here is the error I received when it loaded the Google Chrome tab, with the zipped file below:
![error](https://user-images.githubusercontent.com/68204564/88984684-41451900-d29c-11ea-8cd0-3ca2a1a97b79.png)

[out_HTML.zip](https://github.com/shahinrostami/chord/files/5004243/out_HTML.zip)

**Comment by shahinrostami** [comment]
Hello @bowrango, the `demo.py` was just a copy and paste from the first example in the GitHub README, it looks like it didn't attach! I downloaded your example HTML file. It points you to line 97 where you can see:

```
      matrix = [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]];
```

which isn't a proper assignment! It looks like this is an issue in your Python script somewhere. Head over to our Discord https://discord.gg/azcASEb wher we can help out with getting things going :) In the meantime I'll close this issue because it doesn't look like a bug with `chord` for now, will re-open otherwise!
