### ISSUE TITLE
Nodes without connections

### ISSUE THREAD

**Issue by fiedl** [shahinrostami/chord#19]
## Scenario

I'm adding a node without connection to the chord diagram.

```python
# python

from chord import Chord

matrix = [
  [0, 1, 0],
  [2, 0, 0],
  [0, 0, 0]
]

names = ["Foo", "Bar", "Without connection"]

Chord(matrix, names).show()
```

In the above example, the node without connection corresponds to the third `names` entry and to the last column and row in the `matrix` containing only zeros.

## Expected Behaviour

The chord diagram shows the labels of all nodes and the connections of the connected nodes. It does not show connections of the unconnected node.

## Observed Behaviour

When adding nodes without connection, the chord diagram does not show any labels or connections.

<img width="718" alt="Bildschirmfoto 2020-10-12 um 14 23 00" src="https://user-images.githubusercontent.com/1679688/95746039-6f7ca700-0c96-11eb-8992-8f3a7f1befbe.png">

## Environment

nteract 0.25.1
Python 3.7.6
chord 0.3.0

**Comment by shahinrostami** [comment]
Hello @fiedl 

`chord` currently doesn't support items without any quantities at all (no occurrence or co-occurrence). What is your desired output for the third item - a thin line indicating with the corresponding label? This sounds like a possible feature in future. Are you using `chord` or `chord pro`?

At the moment I'm working on an update that contains better error logging, e.g. in this case the user would be informed about the missing data.

**Comment by fiedl** [comment]
Thank you for the quick reply! I'm using the free chord, but I would be willing to pay for chord pro if necessary — despite my work being scientific and open source.

Indicating the unconnected nodes with zero-width line would be fine. Even better for my use case would be to set the width (or percentage of the circle) for each node manually. This would allow me to have the node size indicate their overall importance/share/percentage regardless of their connections to other nodes.

**Comment by shahinrostami** [comment]
Happy to hear you're using `chord` for scientific work!

I asked because `chord` is on a feature freeze right now, with the upcoming update to be on better error messages. `chord pro` is still getting new features, with requests being accepted by `chord pro` owners too! It's only a small cost but it seems to be enough to fund some continued work on the project. You can check out `chord pro` here https://datacrayon.com/shop/product/chord-pro/!

Labelling connectionless items should be possible!  I'm on discord here https://discord.com/invite/nsezsyb if you want to drop by.

**Comment by shahinrostami** [comment]
Hello @fiedl 

I've pushed a quick solution to this in `chord pro` (https://datacrayon.com/shop/product/chord-pro/!), that is, some support for unconnected nodes.

It requires an update to `chord 0.3.1` (Python) which has disabled `wrap_labels` by default.

Here is the output from your example code above:

<img width="671" alt="Screenshot 2020-11-03 at 19 16 33" src="https://user-images.githubusercontent.com/15690380/98030550-1a513280-1e09-11eb-918e-2c0a167e2f8b.png">

**Comment by fiedl** [comment]
Thank you
