### ISSUE TITLE
How to show custom hover message?

### ISSUE THREAD

**Issue by stefaneidelloth** [shahinrostami/chord#22]
I would like to show a message "The flow between $source and $target is $value"

**Comment by shahinrostami** [comment]
Hello! Are you using Chord Pro (https://datacrayon.com/shop/product/chord-pro/)?

If so - you can use the `verb` and `noun` parameters to change the following template:

```
{source} and {target}
{verb} {num_instances} {noun}
```

e.g. the default is

```
{source} and {target}
occur together in {num_instances} instances
```

Please feel free to join us on https://discord.com/invite/nsezsyb to discuss potential new features!
