### ISSUE TITLE
Directed chord diagrams

### ISSUE THREAD

**Issue by srinivvenkat** [shahinrostami/chord#26]
Thanks for the easy to use, excellent package! Is there a way to visualize directed flows/dependencies?
Examples:
https://observablehq.com/@d3/directed-chord-diagram
https://observablehq.com/@d3/chord-dependency-diagram?collection=@d3/d3-chord

I see there's a symmetric tag but that doesn't accomplish this.

**Comment by shahinrostami** [comment]
Hi @srinivvenkat , I'm glad you're enjoying the `chord` package. 

As you said, `symmetric=False`, is the closest to achieving this right now

<img width="608" alt="Screenshot 2020-11-21 at 13 13 16" src="https://user-images.githubusercontent.com/15690380/99878641-ee9ebc80-2bfe-11eb-910b-b6afa230ab4d.png">

I can put this on the list as an enhancement - what do you think is missing? Is it the arrow-ends and colours?

**Comment by srinivvenkat** [comment]
Thanks for considering the suggestion. I think the simplest version doesn't even need an arrow, and retains the 'source' color for the entire length (instead of the gradient as it is right now). Arrow would make the incoming and outgoing distinction more apparent.

Another thing that will come up when dealing with directed graphs is the arc corresponding to each 'node' will vary depending on whether inflows or outflows are being visualized. The arc length will be proportional to the row or column sum as appropriate.

**Comment by shahinrostami** [comment]
I see - I just had a closer look to see how this would be implemented in `chord pro`, and it's more different than I originally thought. I'll have a think about how to proceed with this one - I may create some kind of 'new feature" roadmap and move this and others like it there to better organise the work on the project.

Thank you for raising it!
