### ISSUE TITLE
Documentation of free vs pro features

### ISSUE THREAD

**Issue by gaardhus** [shahinrostami/chord#27]
Thanks for a great package! 

I'm trying to modify my chord by changing verb, noun and title using the free version, but nothing happens. I guess this might be because these are PRO features, but can't really find any information on which features from the python module are free and which are pro.

Are the "only" free features those described in this section (https://github.com/shahinrostami/chord#defaults)? If so, some clarification would be nice, and would also serve as an "advertisement" of what the pro features actually contain.

**Comment by shahinrostami** [comment]
Hello @gaardhus 

Many thanks for the feedback - it really is a great idea.

I'm working on the error handling and soon the documentation in an effort to bring everything together ahead of a front-end for creating Chord Diagrams with `chord pro` using a web app. If you have a `chord pro` license ahead of the launch, you will get access to that for free as well!

In the meantime I've updated this part of the README https://github.com/shahinrostami/chord/blob/master/README.md#defaults to clearly indicate what is available and what isn't. I hope that clarifies everything!
