### ISSUE TITLE
License: AGPL

### ISSUE THREAD

**Issue by guettli** [shahinrostami/chord#29]
Hi,

I integrated you library into my application to create nice chord diagrams.

Now I see that you use the AGPL license.

I don't work for google, but that's interesting [AGPL not allowed](https://opensource.google/docs/using/agpl-policy/)

Does this mean I need to open source my application?

**Comment by shahinrostami** [comment]
Hello @guettli ,

`chord` (free) does indeed use the AGPL license.

`chord` (pro) doesn't. Check it out here (https://datacrayon.com/shop/product/chord-pro/), it's a lifetime license which doesn't have the open source requirement.

**Comment by guettli** [comment]
Thank you. Unfortunately does my employer not allow me to use AGPL software. I will use [holoviews Chord](https://holoviews.org/reference/elements/bokeh/Chord.html) now. 

Thank you for your fast reply.

**Comment by shahinrostami** [comment]
No problem @guettli .

To be clear, `chord pro` is not AGPL. That is just `chord free`.
