### ISSUE TITLE
API error when creating several 

### ISSUE THREAD

**Issue by NilsErlanson** [shahinrostami/chord#30]
Hi,
I've bought the PRO version of chord and integrated it to a web interface where I need to create several chord diagrams. After I've created some diagrams I get thrown an API error exception and need to restart the creation of the diagrams.

Thanks for a beautiful visualization package.

**Comment by shahinrostami** [comment]
Hello @NilsErlanson 

I'm glad you like it!

The error reporting will be better in future, but in the meantime I can try help you navigate this issue. It seems to be an error with the input. Some errors you're receiving are:

`TypeError: can only concatenate str (not "list") to str`

`TypeError: unsupported operand type(s) for /: 'list' and 'int'`

If you pop onto the Discord, https://discord.gg/nsezsyb, I can take a look at your input and see if I can spot the issue!
