### ISSUE TITLE
Too many requests made to chord free

### ISSUE THREAD

**Issue by FilipKon** [shahinrostami/chord#31]
Hi,

I wanted to ask why I'm getting too many requests, when I almost didn't do any chord diagrams ? There was also nowhere listed that there is a limit of doing chord diagrams. Just that there are not so many options for the free package, but still I should be able to make some simple diagrams or not?

Best regards,
Filip

**Comment by shahinrostami** [comment]
Hi @FilipKon ,

I hope you and yours are well and safe.

Are you seeing the rate-limiting error immediately? 

Chord and Chord Pro were moved into the same service to avoid duplicate maintenance efforts. I was caught off-guard by the surprising number of requests made per minute, e.g. sometimes hundreds, so rate-limiting was introduced to ensure availability of the service.

Check out the new Chord Pro features here https://datacrayon.com/posts/statistics/data-is-beautiful/chord-pro-features-for-chord-diagrams/. If it's useful to you - you can get the lifetime license which may be more suitable if you are generating chord diagrams more often.

If it isn't rate-limiting that you're facing and you believe it's a bug - please reply to this and I'll re-open it to investigate further!

**Comment by FilipKon** [comment]
Hi @shahinrostami,

I hope you and yours are also well and safe.

So in my IDE I'm getting the Error API Error and when I open the HTML file it says Rate Limit exceeded. But does it mean that when I created let's say 10 diagrams that I will get blocked forever?  Because also after waiting 2-3 days I couldn't do even 1 diagram.

Best regards,
Filip

**Comment by shahinrostami** [comment]
@FilipKon That doesn't sound right... once you hit a rate-limit, it should only last 1 hour (maximum). 

Can you drop by our Discord @ https://discord.com/invite/nsezsyb ? I can try to work with you to see what's going on. One thing I forgot to ask - have you updated your Chord package?

**Comment by FilipKon** [comment]
@shahinrostami  Sure sounds good. Yesterday I removed Chord and installed it again, but I still had the error. So I think I have the newest version. I have right now 0.10.2 if thats the newest one.
