### ISSUE TITLE
Correlation matrix

### ISSUE THREAD

**Issue by DushyantSahoo** [shahinrostami/chord#32]
Hi,

Is it possible to make a chord diagram of a sparse correlation matrix? I tried plotting but the results were not as expected. I think, it doesn't have the functionality to use negative values might be due definition of chord diagrams, I might be wrong.

Thank You,
Dushyant Sahoo

**Comment by shahinrostami** [comment]
Hi Dushyant,

I hope you and yours are well!

Chord diagrams, at least the ones in this package, are for visualising a co-occurrence matrix. I've seen them hacked about to represent something similar, but you're right that negative values have no defined behaviour.

I'm interested in the idea...  if simply adding support for negative values will open up a whole new possibility for visualisation. How do you see negative quantities represented in a chord diagram?

I'll close this for now as it isn't a bug, but please do reply with your ideas and I may be able to make it happen!

All the best,

Shahin
