### ISSUE TITLE
Chord does not display in Jupter notebook - OS - Windows

### ISSUE THREAD

**Issue by akdeepak** [shahinrostami/chord#33]
Dear Dr.Shahin

I have used beautiful chart of chord in linux machines jupyter notebook , now i would like to showcase the chord diagrams to my business team on windows os , but the the chart does not displays the output rather it displays " please upgrade your package/crate) please find the snapshot

Chord version - 0.12.0

<img width="462" alt="chord_issue" src="https://user-images.githubusercontent.com/19904559/105358353-14a30600-5c1c-11eb-8f68-6bd644c4a51e.PNG">

**Comment by shahinrostami** [comment]
Hello @akdeepak 

For commercial use you need to pick up a Chord Pro license (https://datacrayon.com/shop/product/chord-pro/)

I would double check the version of Chord, try `pip uninstall chord` and `pip install chord` again. You should only see that message on lower versions!

**Comment by akdeepak** [comment]
I have already tried pip uninstall chord and pip install chord , no luck , sure will for the licensed version post the first level of showcasing the chart to business teams , 
Could you please tell me any other solutions. Thanks in advance
