### ISSUE TITLE
When can the chord-free support Chinese？

### ISSUE THREAD

**Issue by CaiCaiYa** [shahinrostami/chord#34]
when the list has Chinese，The relevant part is garbled of the generated html file。Or my usage is wrong？I don`t know

**Comment by shahinrostami** [comment]
@CaiCaiYa There's only one way to find out! 

Can you share as much as you can with me so I can investigate? It can be tough to track. In the first instance can I have:

- The code you are using to generate the diagram (please remove your license details)
- The HTML file that is being outputted (please attach it too)

**Comment by CaiCaiYa** [comment]
Two parameters:
list=['SFG额上回', 'MFG额中回', 'IFG额下回', 'OrG眶回', 'PrG中央前回','PCL中央旁小叶']

matrix = [
    [0, 5, 6, 4, 7, 4],
    [5, 0, 5, 4, 6, 5],
    [6, 5, 0, 4, 5, 5],
    [4, 4, 4, 0, 5, 5],
    [7, 6, 5, 5, 0, 4],
    [4, 5, 5, 5, 4, 0],
]
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
![Garbled  ](https://user-images.githubusercontent.com/45023683/106464586-cb806b00-64d3-11eb-9ebb-563751abc823.png)
[chord.txt](https://github.com/shahinrostami/chord/files/5904148/chord.txt)

**Comment by CaiCaiYa** [comment]
1. thank you for your reply
2. I use pycharm to do this work.
3. the encoding format of pycharm and html file is utf-8.  
4. If there is a problem with my encoding format settings ,please tell me how to solve

**Comment by shahinrostami** [comment]
I'm on lunch right now but when I finish work I'll use the data you shared above and try to reproduce the error. I'll also share any encoding I used if it works. I don't use pycharm but I shouldn't think that causes an error!

I'll keep this issue open and update when I have something 👍

**Comment by shahinrostami** [comment]
Hi @CaiCaiYa 

Check below where I copied over your inputs and generated the output without garbled text. I think it must be an issue with pycharm in this case, which I don't have much experience with. Can you check it with their support/community to see what they think it may be?
 
<img width="316" alt="Screenshot 2021-02-01 at 19 16 52" src="https://user-images.githubusercontent.com/15690380/106506820-2315db00-64c2-11eb-94d1-a86211bc399a.png">

**Comment by CaiCaiYa** [comment]
thank you very much.
I will try other ways to solve this problem.
