### ISSUE TITLE
Credit flag no longer working

### ISSUE THREAD

**Issue by zedrdave** [shahinrostami/chord#38]
It seems there was a regression introduced: passing `credit=False` to Chord pro no longer produces a version without credit (it has less text than the `credit=True` version, but still some)…
From looking at the client code: the problem is on the server side…

(sorry to bother you again! Hopefully this is an easy one to fix 😅)

**Comment by zedrdave** [comment]
I think you are in the middle of tinkering with this, so just on the off-chance that can help, I think you got the wrong commenting style for the injected JS: 😉

<img width="692" alt="Screenshot 2021-04-11 at 18 45 09" src="https://user-images.githubusercontent.com/746979/114313272-3367b900-9af6-11eb-9283-4feb14dd0da8.png">

**Comment by shahinrostami** [comment]
> I think you are in the middle of tinkering with this, so just on the off-chance that can help, I think you got the wrong commenting style for the injected JS: 😉
> 
> <img alt="Screenshot 2021-04-11 at 18 45 09" width="692" src="https://user-images.githubusercontent.com/746979/114313272-3367b900-9af6-11eb-9283-4feb14dd0da8.png">

You guessed correctly! I was in middle of testing it and then I had to answer the door... one moment!

**Comment by zedrdave** [comment]
No worries. I'm taking a break anyway…
Just didn't want you to spend time wondering why code wasn't working… because of a silly commenting format error (I know how that goes) 😅

**Comment by shahinrostami** [comment]
> No worries. I'm taking a break anyway…
> Just didn't want you to spend time wondering why code wasn't working… because of a silly commenting format error (I know how that goes) 😅

All done now 😃 if you're interested, that mistake was me forgetting single-line Mako comments were with "##"! Thank you for pointing it out
