### ISSUE TITLE
Is there a way to increase the size of the connection to make it appear more visible?

### ISSUE THREAD

**Issue by Sathvik833** [shahinrostami/chord#44]
how can I change the size of the connections to make the connections appear more visible
![Screenshot 2021-06-24 at 01-44-25 Chord Diagram](https://user-images.githubusercontent.com/61035070/123215170-bbbaf080-d48d-11eb-93a3-a459edcf4248.png)

**Comment by shahinrostami** [comment]
Hello @Sathvik833 ! At the moment the only way to change the size of connections is by increasing their value proportionally in the co-occurrence matrix. I can see perhaps a need for a "minimum thickness" at some point, I'll add that onto my feature list for future!
