### ISSUE TITLE
No longer functional?

### ISSUE THREAD

**Issue by RodolfoFigueroa** [shahinrostami/chord#45]
When I try to generate an HTML file from a diagram, the following message appears:

```
Plotapi.com has launched
Check out Plotapi.com where you'll find more than just Chord Diagrams!
```

Does this mean this package has been discontinued?

**Comment by shahinrostami** [comment]
Hi

`Chord Pro` still works for license holders.

`Chord Free` still works as it did previously, however, it is being used so frequently that the rate-limit is almost always being hit.

All new features will only be added to [Plotapi](https://plotapi.com). You can see some of the [latest Chord features here](https://plotapi.com/gallery/posts/showcase/league-of-legends-classes-with-plotapi-chord/).
