### ISSUE TITLE
Call to Chord(...).show() displays only ad for PlotApi

### ISSUE THREAD

**Issue by jkolom** [shahinrostami/chord#46]
Having had to reinstall fresh my computer (Anaconda, plotly, chord), the output of Chord(...).show() is now the picture below.

![image](https://user-images.githubusercontent.com/520942/131331781-210c0b55-1fa6-45e7-a743-cdc016f2501d.png)

I just checked, and it seems like the option to plot offline has been removed since 0.5.0, which basically makes this library unusable where data should not be sent outside (basically any company).

**Comment by shahinrostami** [comment]
Hello 

Sorry if brief, unfortunately have covid.

Chord and now Plotapi have been service-based for a while you are right. More details in README. Chord Pro (paid version) has always been this way too.

You're right if the data cannot leave your network you won't be able to use this. I recommend Plotly (offline mode) or writing in d3js directly.

All the best
