### ISSUE TITLE
.to_png()

### ISSUE THREAD

**Issue by Sathvik833** [shahinrostami/chord#47]
![image](https://user-images.githubusercontent.com/61035070/132613807-40e9a921-8d3d-4f5c-b4a8-3cd5db710b2d.png)

**Comment by Sathvik833** [comment]
why is saying this when I do .to_png()

**Comment by Sathvik833** [comment]
does the .to_png() not work

**Comment by Sathvik833** [comment]
if it does work how do i get it

**Comment by shahinrostami** [comment]
Hi - the server side rendering of PNGs and PDFs was an experimental feature in Chord Pro. If you'd like those features and more please visit https://plotapi.com
