### ISSUE TITLE
Invisible labels 

### ISSUE THREAD

**Issue by deeplook** [shahinrostami/chord#6]
I'm using Chord 0.0.9 with JupyterLab 2.1.0, but I don't see the labels outside the big circle. Any idea?

**Comment by shahinrostami** [comment]
> I'm using Chord 0.0.9 with JupyterLab 2.1.0, but I don't see the labels outside the big circle. Any idea?

I know what you mean, can you tell me your browser what version? If it’s Firefox, I have seen this happen all the time... unfortunately that’s the case with the d3-chord code we wrap around. Let me know and I’ll take a look!

Shahin

**Comment by deeplook** [comment]
Yes, I'm on Firefox. Sorry for not providing that info immediately.

**Comment by shahinrostami** [comment]
I will take a look, but I think it may be an issue further up the line of dependencies. Will update when I can

**Comment by shahinrostami** [comment]
At the moment it looks like it’s an issue with d3-chord on Firefox. If I see a fix I’ll update the referenced script
