### ISSUE TITLE
Fontsize of the labels

### ISSUE THREAD

**Issue by ynskoroglu** [shahinrostami/chord#7]
Hello,
I am trying populate diagram with varying length labels, ranging from 4 to 20. In addition to that group with short long label has fewer instances. Thus labels overlaps and become unreadable.

I have 3 solutions coming to my mind, as possible solutions:
1) Automatically change font size according size of the groups.
2) Set sizes for each specific label as a list like names instances.
3) Divide labels into two separate lines. 

Related Example:
![image](https://user-images.githubusercontent.com/37922796/80243083-319bb000-866f-11ea-9372-dbfe54c0debb.png)

**Comment by shahinrostami** [comment]
Hello,

Thank you for checking out Chord and raising the issue.  Using the mobile app so please excuse the brevity.

For this scenario we have the wrap labels flag, I.e. ` wrap_labels=False`. Try it out and let me know what you think, does it solve your issue?

All the best,

Shahin

**Comment by ynskoroglu** [comment]
Hello Shahin, 

Unfortunately this doesn't resolve the situation, as I already use wrap_labels while generating first file. I attached the resulting file for you to, you can obtain matrix and labels within file for replication.

[Network_Chord.zip](https://github.com/shahinrostami/chord/files/4534126/Network_Chord.zip)

**Comment by shahinrostami** [comment]
> Hello Shahin,
> 
> Unfortunately this doesn't resolve the situation, as I already use wrap_labels while generating first file. I attached the resulting file for you to, you can obtain matrix and labels within file for replication.
> 
> [Network_Chord.zip](https://github.com/shahinrostami/chord/files/4534126/Network_Chord.zip)

Can you share the code you used to generate that output? It looks like your labels still wrapping, which shouldn't happen with `wrap_labels=False`

**Comment by shahinrostami** [comment]
Please re-open the issue if it comes up again
