### ISSUE TITLE
output from .to_html() missing 'details' value

### ISSUE THREAD

**Issue by Joey5729** [shahinrostami/chord#8]
![image](https://user-images.githubusercontent.com/18487866/82394534-50475980-9a17-11ea-9af5-199b83d1f36c.png)

I was able to fix it by just putting "" after it.
Without it my browser raised an error and the page was blank.

**Comment by shahinrostami** [comment]
@Joey5729 Thanks for raising this issue.

The details parameter was introduced as an option in the latest publication of `chord`. Can you check that you're on `0.0.11`?

**Comment by Joey5729** [comment]
I was on 0.0.10, it worked correctly on 0.0.11. Sorry!

**Comment by shahinrostami** [comment]
Happy it's resolved :)
