### ISSUE TITLE
About the import issues

### ISSUE THREAD

**Issue by ThomasVercetti** [shahinrostami/chord#9]
When I was trying to import the Chord， some issues occurred:
Traceback (most recent call last):
  File "e:/anaconda/Anaconda/lib/site-packages/chord/__init__.py", line 21, in <module>
    template = urllib.request.urlopen(template_url).read()
  File "E:\anaconda\Anaconda\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "E:\anaconda\Anaconda\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "E:\anaconda\Anaconda\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "E:\anaconda\Anaconda\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "E:\anaconda\Anaconda\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "E:\anaconda\Anaconda\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060]>
Could you please solve the issues?

**Comment by shahinrostami** [comment]
Hi, can you confirm which version you're on? 

In the README I've put a notice about the recent breaking changes, such that everything moving forward would be backwards compatible!

Try
```
pip uninstall chord
pip install chord
```
and let me know if it works!

**Comment by ThomasVercetti** [comment]
Well, the version of chord is 0.0.11, and I tried the pip command, however it didn't works.



---Original---

**Comment by shahinrostami** [comment]
> Well, the version of chord is 0.0.11, and I tried the pip command, however it didn't works.
> […](#)
> ---Original--- From: "Dr. Shahin Rostami"<notifications@github.com&gt; Date: Sun, May 24, 2020 19:56 PM To: "shahinrostami/chord"<chord@noreply.github.com&gt;; Cc: "Author"<author@noreply.github.com&gt;;"ThomasVercetti"<1246377298@qq.com&gt;; Subject: Re: [shahinrostami/chord] About the import issues (#9) Hi, can you confirm which version you're on? In the README I've put a notice about the recent breaking changes, such that everything moving forward would be backwards compatible! Try pip uninstall chord pip install chord and let me know if it works! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I think that may be the problem. Check the current version of `chord`, which is `0.0.13` (https://pypi.org/project/chord/). Once you update the package, it should be fine.
